FROM python:3.12-slim

RUN pip install \
    dagster==1.10.15 \
    dagster-graphql==1.10.15 \
    dagster-webserver==1.10.15 \
    dagster-postgres==0.26.15 \
    dagster-docker==0.26.15 \
    watchdog==4.0.2 \
    dagster-aws==0.26.15

# Set DAGSTER_HOME to an absolute path
ENV DAGSTER_HOME=/opt/dagster_home

RUN mkdir -p $DAGSTER_HOME

COPY . $DAGSTER_HOME

RUN pip install --upgrade pip \
 && pip install -r $DAGSTER_HOME/requirements.txt

WORKDIR $DAGSTER_HOME